trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: vercel-deployment-task@1
  inputs:
    vercelProjectId: 'prj_QDoHobTNU0iH9ynJURF0DE8GpcAx'
    vercelOrgId: 'yMTJOTaXUwAyspJVmFJTXBa0' 
    vercelToken: $(VERCEL_TOKEN)
    production: true
