export const diet = {
  dietData: {
    totalCalories: 2200,
    userMaintenanceCalories: 2000,
    totalProtein: 150,
    totalCarbs: 250,
    totalFat: 80,
  },
  meals: [
    {
      name: "Hearty Oatmeal Breakfast",
      description:
        "A nutritious and filling breakfast with oatmeal, egg whites, and blueberries.",
      totalCalories: 500,
      totalProtein: 30,
      totalCarbs: 60,
      totalFat: 15,
      mealTimePrep: 15,
      recipes: [
        "Cook oatmeal with water or milk according to package instructions.",
        "Scramble or cook egg whites separately.",
        "Add blueberries to the oatmeal and top with cooked egg whites.",
      ],
      foods: [
        {
          name: "Oatmeal",
          quantity: 50,
          unit: "g",
          protein: 5,
          carbs: 25,
          fat: 3,
        },
        {
          name: "Egg Whites",
          quantity: 100,
          unit: "g",
          protein: 10,
          carbs: 0,
          fat: 0,
        },
        {
          name: "Blueberries",
          quantity: 100,
          unit: "g",
          protein: 1,
          carbs: 15,
          fat: 0,
        },
      ],
    },
    {
      name: "Grilled Chicken and Veggie Bowl",
      description:
        "A balanced and flavorful lunch with grilled chicken, brown rice, and roasted broccoli.",
      totalCalories: 600,
      totalProtein: 40,
      totalCarbs: 70,
      totalFat: 20,
      mealTimePrep: 30,
      recipes: [
        "Season and grill the chicken breast.",
        "Cook brown rice according to package instructions.",
        "Toss broccoli with olive oil, salt, and pepper, and roast in the oven.",
        "Assemble the bowl with grilled chicken, brown rice, and roasted broccoli.",
      ],
      foods: [
        {
          name: "Grilled Chicken Breast",
          quantity: 150,
          unit: "g",
          protein: 30,
          carbs: 0,
          fat: 5,
        },
        {
          name: "Brown Rice",
          quantity: 100,
          unit: "g",
          protein: 3,
          carbs: 25,
          fat: 1,
        },
        {
          name: "Broccoli",
          quantity: 100,
          unit: "g",
          protein: 3,
          carbs: 5,
          fat: 0,
        },
      ],
    },
    {
      name: "Salmon and Sweet Potato Dinner",
      description:
        "A satisfying dinner featuring baked salmon, roasted sweet potato, and sautéed asparagus.",
      totalCalories: 700,
      totalProtein: 50,
      totalCarbs: 80,
      totalFat: 30,
      mealTimePrep: 45,
      recipes: [
        "Season the salmon fillets and bake in the oven.",
        "Peel and cut the sweet potato into cubes, toss with oil, salt, and pepper, and roast.",
        "Sauté the asparagus in a pan with garlic and olive oil.",
        "Serve the salmon, roasted sweet potato, and sautéed asparagus together.",
      ],
      foods: [
        {
          name: "Salmon Fillet",
          quantity: 150,
          unit: "g",
          protein: 30,
          carbs: 0,
          fat: 15,
        },
        {
          name: "Sweet Potato",
          quantity: 200,
          unit: "g",
          protein: 4,
          carbs: 40,
          fat: 0,
        },
        {
          name: "Asparagus",
          quantity: 100,
          unit: "g",
          protein: 3,
          carbs: 5,
          fat: 0,
        },
      ],
    },
  ],
};
