import { IndustryOption } from "../types/industry";

export const industryOptions: IndustryOption[] = [
  { value: "agriculture", label: "Agriculture" },
  { value: "automotive", label: "Automobile" },
  { value: "construction", label: "Construction" },
  { value: "education", label: "Éducation" },
  { value: "energy", label: "Énergie" },
  { value: "finance", label: "Finance" },
  { value: "government", label: "Gouvernement" },
  { value: "healthcare", label: "Santé" },
  { value: "health-wellness", label: "Santé et bien-être" },
  { value: "hospitality", label: "Hôtellerie" },
  { value: "legal", label: "Juridique" },
  { value: "manufacturing", label: "Fabrication" },
  { value: "media", label: "Médias et divertissement" },
  { value: "nonprofit", label: "Organisme à but non lucratif" },
  { value: "other", label: "Autre" },
  { value: "professional-services", label: "Services professionnels" },
  { value: "real-estate", label: "Immobilier" },
  { value: "retail", label: "Vente au détail" },
  { value: "technology", label: "Technologie" },
  { value: "telecommunications", label: "Télécommunications" },
  { value: "transportation", label: "Transport" },
];
